<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="databaseOperationsSchema" nsURI="http://es.um.uschema.code.metamodels/dboSchema"
    nsPrefix="databaseOperationsSchema">
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseOperationsSchema">
    <eStructuralFeatures xsi:type="ecore:EReference" name="databaseOperations" upperBound="-1"
        eType="#//DatabaseOperation" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containers" upperBound="-1"
        eType="#//Container" containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DatabaseOperation" abstract="true">
    <eStructuralFeatures xsi:type="ecore:EReference" name="followingDatabaseOperation"
        upperBound="-1" eType="#//DatabaseOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="precedingDatabaseOperation"
        upperBound="-1" eType="#//DatabaseOperation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="statement" eType="ecore:EClass ../../es.um.uschema.code.metamodels.code/model/code.ecore#//Statement"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetingParameter" eType="#//OperationParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DataStructure">
    <eStructuralFeatures xsi:type="ecore:EReference" name="fields" upperBound="-1"
        eType="#//Field" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="container" eType="#//Container"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Field">
    <eStructuralFeatures xsi:type="ecore:EReference" name="type" eType="#//Type" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="duplicatedField" eType="#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Type" abstract="true"/>
  <eClassifiers xsi:type="ecore:EClass" name="Attribute" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Reference" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetContainer" eType="#//Container"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetField" eType="#//Field"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="referenceType" eType="#//Attribute"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Container">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataStructures" upperBound="-1"
        eType="#//DataStructure" containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Composition" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EReference" name="dataStructure" eType="#//DataStructure"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Read" eSuperTypes="#//DatabaseOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="resultDataStructure" eType="#//DataStructure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Insert" eSuperTypes="#//DatabaseOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="insertDataStructure" upperBound="-1"
        eType="#//DataStructure"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Update" eSuperTypes="#//DatabaseOperation">
    <eStructuralFeatures xsi:type="ecore:EReference" name="updateParameter" eType="#//OperationParameter"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Delete" eSuperTypes="#//DatabaseOperation"/>
  <eClassifiers xsi:type="ecore:EClass" name="OperationParameter">
    <eStructuralFeatures xsi:type="ecore:EReference" name="parameterFields" upperBound="-1"
        eType="#//Field"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Collection" eSuperTypes="#//Type">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="collectionType" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="types" upperBound="-1"
        eType="#//Type" containment="true"/>
  </eClassifiers>
</ecore:EPackage>
